### PR TITLE
Development

### PR DESCRIPTION
**Pull request by lololosys**
Your code is awful. I'm sorry. I gotta help this project for the sake of open soure!
May you please accept this clean C version of ProReversing?

### CODE REVIEW

**Comment by mrexodia** [comment]
I dont see any reason for a C version but sure I can accept the pull
request. It might be a good idea to send it to the original author instead
though :) I just added some stuff for my own tests.

**Comment by mrexodia** [comment]
Here is the original repository https://github.com/eschweiler/ProReversing

This project is also a horrible anti-anti library. Take a look at ScyllaHide instead: https://bitbucket.org/NtQuery/scyllahide

**Comment by lololosys** [comment]
Oh shit, I didnt notice it. Anyway, I agree, this could be a C++ project, I prefer C.
ScyllaHide looks almost good(there are still things to work on).
Maybe instead of trying make ProReversing good and rewrite it, more smart thing to do is try to help with ScyllaHide since there is no need for 2 projects that do the same :+1:

**Comment by mrexodia** [comment]
Yea, ScyllaHide needs some fixes but dont bother coding style fixes. Go for
features instead.

**Pull request merged**
